### ISSUE TITLE
does it show any parking page after using your ns?

### ISSUE THREAD

**Issue by anantsparrow** [nhairs/domain-park#1]

**Comment by nhairs** [comment]
By default the server does not show any parking page as it does not include a web server.

If this is something you want you'd need to have your own web-server to deliver the page, we'd then need to update domain-park to be able to add `A`/`AAAA` that you could then point to your web-server.

**Comment by anantsparrow** [comment]
Hey there, thank you for the reply, i tried installing it via docker and
manual , after installing it via pip, it says command not found? What could
be the reason?

**Comment by anantsparrow** [comment]
Update, i installed it correctly, updated the ns to inboxbot.net, but it is not resolving to many regions what could be the reason?

**Comment by nhairs** [comment]
If you're using a domain for the nameservers (e.g. ns.example.com) the most likely cause is needing to setup [glue records](https://serverfault.com/questions/309622/what-is-a-glue-record).

If your name was previously in use it is likely also a caching issue. Pretty much all TLDs will set a TTL of 48 hours.

**Comment by anantsparrow** [comment]
Hey there solved the issue, made what i was thinking to build, https://suspend.page
